import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useLanguage } from '../LanguageContext.jsx';
import { fetchSpots } from '../services/tourApi.js';

function Home() {
  const { copy } = useLanguage();
  const [spots, setSpots] = useState([]); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { fetchSpots().then((data) => { setSpots(data.slice(0, 6)); setError(''); }).catch(() => setError(copy.home.error)).finally(() => setIsLoading(false)); }, [copy.home.error]);
  const heroImage = useMemo(() => spots.find((spot) => spot.image)?.image, [spots]); const featuredSpots = spots.slice(0, 3);
  return <section className="home-board"><div className="planner-shell"><section className="planner-chat"><p className="eyebrow">{copy.home.eyebrow}</p><h1>{copy.home.title.split('\n').map((line) => <span key={line}>{line}<br /></span>)}</h1><p className="hero-copy">{copy.home.intro}</p><div className="prompt-card"><div className="assistant-avatar">B</div><div><p className="prompt-label">{copy.home.planner}</p><p>{copy.home.plannerBody}</p></div></div><div className="quick-chips"><span>Sea & walks</span><span>Photo spots</span><span>Night views</span></div><Link className="button" to="/spots">{copy.home.viewSpots}</Link></section><aside className="trip-preview"><div className="preview-map" style={heroImage ? { backgroundImage: `url(${heroImage})` } : undefined} aria-label="Busan preview map"><div className="map-pin primary-pin">1</div><div className="map-pin secondary-pin">2</div><div className="map-pin tertiary-pin">3</div></div><div className="itinerary-panel"><div className="section-heading compact-heading"><p className="eyebrow">Today board</p><h2>{copy.home.board}</h2></div>{isLoading && <p className="status-text">{copy.home.loading}</p>}{error && <p className="status-text">{error}</p>}{!isLoading && !error && <div className="mini-itinerary">{featuredSpots.map((spot, index) => <Link className="mini-stop" key={spot.id} to={`/spots/${spot.id}`}><span>{index + 1}</span><div><strong>{spot.title}</strong><p>{spot.area || spot.address || copy.common.busan}</p></div></Link>)}</div>}</div></aside></div><nav className="home-service-nav" aria-label="Main services"><Link className="service-tile" to="/events"><span>01</span><strong>{copy.nav.events}</strong><small>Festivals happening in Busan</small></Link><Link className="service-tile" to="/spots"><span>02</span><strong>{copy.nav.spots}</strong><small>Explore popular places</small></Link><Link className="service-tile" to="/stories"><span>03</span><strong>{copy.nav.stories}</strong><small>Stories held by each place</small></Link><Link className="service-tile" to="/map"><span>04</span><strong>{copy.nav.map}</strong><small>See places at a glance</small></Link></nav><section className="today-section"><div className="section-heading"><p className="eyebrow">Explore</p><h2>{copy.home.explore}</h2></div>{isLoading && <p className="status-text">{copy.home.loading}</p>}{error && <p className="status-text">{error}</p>}{!isLoading && !error && <div className="card-grid featured-grid">{featuredSpots.map((spot) => <Link className="spot-card" key={spot.id} to={`/spots/${spot.id}`}>{spot.image ? <img src={spot.image} alt={spot.title} /> : <div className="image-placeholder">Busan</div>}<div><p className="category">{spot.area || copy.common.busan}</p><h3>{spot.title}</h3><p>{spot.shortDescription || spot.address || copy.common.noInfo}</p></div></Link>)}</div>}</section></section>;
}
export default Home;
